# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hitTestPractice' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hitTestPractice

  target 'hitTestPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hitTestPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
